
//  登录
export const SET_USERNAME = 'SET_USERNAME'

export const SET_NICKNAME = 'SET_NICKNAME'

export const SET_AVATARURL = 'SET_AVATARURL'

export const SET_PASSWORD = 'SET_PASSWORD'

export const SET_COLLECTSONGLIST = 'SET_COLLECTSONGLIST'

export const SET_COLLECTSONG = 'SET_COLLECTSONG'

export const SET_COLLECTSINGER = 'SET_COLLECTSINGER'

//  歌曲
export const SET_SINGER = 'SET_SINGER'

export const SET_PLAY_STATE = 'SET_PLAY_STATE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_AUDIO = 'SET_AUDIO'

export const SET_PLAYHISTORYLIST = 'SET_PLAYHISTORYLIST'